added shopping cart
dmytrocherepov/BookStoreApp pull request #10
Opened 2023-11-07 23:45 UTC by dmytrocherepov

2023-11-09 11:24 UTC, viacheslav-torbin commented on src/main/java/com/example/bookstoreapp/dto/shoppingcart/CartItemUpdateDto.java
You use 2 different styles for records, pls pick one

2023-11-10 15:57 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/dto/shoppingcart/CartItemUpdateDto.java
> +public record CartItemUpdateDto(
A little bit confusing naming. Is it request or Response? 
CartItemUpdateRequestDto

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/dto/shoppingcart/CartDto.java
> +public record CartDto(
ShoppingCartDto

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/service/ShoppingCartService.java
> +@Service
It's redundant annotation here

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/service/impl/CategoryServiceImpl.java
> -        if (categoryRepository.existsByName(categoryDto.name())) {
I didn't find any code related to Category. Remove it from this PR

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        cartItem.setBook(bookRepository.findById(requestDto.bookId()).orElseThrow(
It's better to create local variable for Book. Code is difficult to read

2023-11-10 15:57 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +    @Override
@Transactional

2023-11-14 15:15 UTC, Elena-Bruyako approved these changes
Good job! Only remove useless annotation!

2023-11-14 15:15 UTC, Elena-Bruyako commented on src/main/java/com/example/bookstoreapp/controller/AuthenticationController.java
> +@Validated
Why you added this annotation if you didn't use validation for PathVariable for example?

2023-11-14 16:50 UTC, merged