Tests1 - category , book
dmytrocherepov/BookStoreApp pull request #22
Opened 2023-12-14 13:59 UTC by dmytrocherepov

2023-12-19 21:37 UTC, OlehReex approved these changes

2023-12-21 15:05 UTC, liliia-ponomarenko requested changes
Good job! 👍 👏  Let’s  fix a few mistakes ;)

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
wow, don’t do it!!!

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/service/impl/BookServiceImpl.java
> +        setCategories(requestDto, book);
why do you duplicate it?

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/service/impl/BookServiceImpl.java
> +        );
you can use isBookExistById

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/BookServiceTest.java
> +
```suggestion
```

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/BookServiceTest.java
> +        when(bookMapper.toBook(requestDto)).thenReturn(book);
do you really need to mock it?  you use spy

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/BookServiceTest.java
> +        );
I see the same object in another method. You can move it to private method

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/CategoryServiceTest.java
> +        when(categoryMapper.toEntity(requestDto)).thenReturn(category);
the same

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/CategoryServiceTest.java
> +        when(categoryMapper.toEntity(requestDto)).thenReturn(category);
the same

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/java/com/example/bookstoreapp/service/CategoryServiceTest.java
> +
```suggestion
```

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/resources/databases/books/add-one-book.sql
> +values (1,1);
add one empty line (check other files)

2023-12-21 15:05 UTC, liliia-ponomarenko commented on src/test/resources/databases/books/add-one-book.sql
> +values (1,'test','test','1234567890',1.25);
```suggestion
VALUES (1,'test','test','1234567890',1.25);
```

2024-01-23 16:31 UTC, liliia-ponomarenko approved these changes
Great job!

2024-02-07 09:10 UTC, merged