added GlobalExceptionHandler , validation
dmytrocherepov/BookStoreApp pull request #4
Opened 2023-10-19 21:08 UTC by dmytrocherepov

2023-10-22 14:19 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-22 14:19 UTC, NazarSmith228 commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
it is better to use `spring-boot-starter-validation`

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/controller/BookController.java
> +    public BookDto getById(@PathVariable @Positive Long id) {
you need to add `@Validated` annotation on your controller class in order to make validation of `@PathVariable, @RequestParam` etc. possible

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/controller/BookController.java
> +    void deleteById(@PathVariable @Positive Long id) {
```suggestion
    public void deleteById(@PathVariable @Positive Long id) {
```

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/controller/BookController.java
>      public BookDto updateBookById(
consider adding response statuses for all your endpoints

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/dto/CreateBookRequestDto.java
> +        @Min(value = 0)
it is better to use `@NotNull @PositiveOrZero`

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/exception/BookApiException.java
> +public record BookApiException(
this is misleading

it seems that this class claims to be an exception, although it is not

it is rather `ErrorResponseWrapper`

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/exception/BookApiException.java
> +        HttpStatus httpStatus,
do you really need status here?

it will be obvious from HTTP response as is

2023-10-22 14:19 UTC, NazarSmith228 commented on src/main/java/com/example/bookstoreapp/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
no need to store status in response body

2023-10-23 10:28 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comment before merging ;)

2023-10-23 10:28 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Can you delete this dependency now?

2023-10-23 10:28 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/dto/CreateBookRequestDto.java
> +        @PositiveOrZero
Let’s  add NotNull

2023-10-23 13:42 UTC, merged