Book category
dmytrocherepov/BookStoreApp pull request #9
Opened 2023-11-06 16:34 UTC by dmytrocherepov

added book category , service , mapper , liquibase

2023-11-07 17:04 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/controller/CategoryController.java
> +
```suggestion
```

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```
you can simplify  it, apply to other endpoints

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/dto/book/CreateBookRequestDto.java
> +        @NotNull
```suggestion
        @NotEmpty
```

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/exception/CategoryException.java
> +public class CategoryException extends RuntimeException {
Don’t  create such exception just use EntityNotFoundException

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/mapper/CategoryMapper.java
> +
```suggestion
```

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/model/Book.java
> +    @ManyToMany
if you use data better add 
```
@ToString.Exclude
@EqualsAndHashCode.Exclude
```

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/repository/category/CategoryRepository.java
> +    void deleteById(Long id);
is it mandatory to record these methods in the repository?

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/service/impl/BookServiceImpl.java
> +    private void setCategories(CreateBookRequestDto requestDto, Book book) {
you should also add it to update method

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/service/impl/CategoryServiceImpl.java
> +
```suggestion
```

2023-11-07 17:04 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookstoreapp/service/impl/CategoryServiceImpl.java
> +        }
Interesting 🤔  but don’t  complicate your solution)

2023-11-08 08:44 UTC, NazarSmith228 requested changes
There are merge conflicts. Pls resolve them first :)

2023-11-08 09:44 UTC, merged

2023-11-08 09:45 UTC, dmytrocherepov commented
solved conflicts